// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentMVC.Models;

namespace StudentMVC.Migrations
{
    [DbContext(typeof(CSDL))]
    partial class CSDLModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("StudentMVC.Models.LopSH", b =>
                {
                    b.Property<int>("Id_Lop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("NameLop")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Lop");

                    b.ToTable("LopSH");
                });

            modelBuilder.Entity("StudentMVC.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Birth")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<int>("Id_Lop")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("Id_Lop");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("StudentMVC.Models.Student", b =>
                {
                    b.HasOne("StudentMVC.Models.LopSH", "LopSH")
                        .WithMany("SVs")
                        .HasForeignKey("Id_Lop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopSH");
                });

            modelBuilder.Entity("StudentMVC.Models.LopSH", b =>
                {
                    b.Navigation("SVs");
                });
#pragma warning restore 612, 618
        }
    }
}
